### ISSUE TITLE
Issue with Streaming Play URL

### ISSUE THREAD

**Issue by ItzTechZack** [dbm-network/mods#202]
Basically, If you want to stream a URL for music it still goes through dispatcher and after some time the bot crashes due to several things

first error is 
```
this.playNext(id);
3|bot  |                                     ^
3|bot  |
3|bot  | TypeError: this.playNext is not a function
3|bot  |     at Object.<anonymous> (C:\Users\ToolsBox\Documents\Discord Bot Projects\Public Bots\RBv2\bot.js:1457:10)
3|bot  |     at StreamDispatcher.emit (events.js:189:13)
3|bot  |     at StreamDispatcher.destroy (C:\Users\ToolsBox\Documents\Discord Bot Projects\Public Bots\RBv2\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:300:30)
3|bot  |     at StreamDispatcher.process (C:\Users\ToolsBox\Documents\Discord Bot
3|bot  |  Projects\Public Bots\RBv2\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:249:12)
3|bot  |     at player.voiceConnection.voiceManager.client.setTimeout (C:\Users\ToolsBox\Documents\Discord Bot Projects\Public Bots\RBv2\node_modules\discord.js\src\client\voice\disp
3|bot  | atcher\StreamDispatcher.js:247:77)
3|bot  |     at Timeout.setTimeout [as _onTimeout] (C:\Users\ToolsBox\Documents\Discord Bot Projects\Public Bots\RBv2\node_modules\discord.js\src\client\Client.js:422:7)
3|bot  |     at ontimeout (t
3|bot  | imers.js:436:11)
3|bot  |     at tryOnTimeout (timers.js:300:5)
3|bot  |     at listOnTimeout (timers.js:263:5)
3|bot  |     at Timer.processTimers (timers.js:223:10)

```
But with this also.. I did have to rewrite it to stop this from happening but there should be a system to check if it is streaming a URL or using the Dispatch Queue system.. Basically a Simple If Statement.

**Comment by Almeeida** [comment]
I will be closing this issue since it's old and hasn't had any recent activity. If the issue persists, feel free to reopen/create a new ticket.
