### ISSUE TITLE
Cleverbot.io just don't work

### ISSUE THREAD

**Issue by marceaupatu123** [dbm-network/mods#206]
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\Marceau\Desktop\papa\cleverbotot\node_modules\cleverbot.io\app.js:16:14)
    at Request.self.callback (C:\Users\Marceau\Desktop\papa\cleverbotot\node_modules\request\request.js:186:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Users\Marceau\Desktop\papa\cleverbotot\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (C:\Users\Marceau\Desktop\papa\cleverbotot\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)

**Comment by Superbrain8** [comment]
for me it works fine. Where did you got your Token?

**Comment by elijah9116** [comment]
I got the same problem and error can you make a video of setting it up?

**Comment by elijah9116** [comment]
Now i'm getting this Bot is ready!
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'cleverbot.io'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'cleverbot.io' does not exist!
Command failed: npm install cleverbot.io --loglevel=error --save
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'cleverbot.io'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'cleverbot.io' does not exist!
Command failed: npm install cleverbot.io --loglevel=error --save
Error with Event "Cleverbot", Action #1: Error: Cannot find module 'cleverbot.io'

**Comment by elijah9116** [comment]
I get this when i try and node
C:\Users\hellow\Desktop\T.A.P Bot\T.A.P Bot>node bot.js
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../../util/Constants'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\hellow\Desktop\T.A.P Bot\T.A.P Bot\actions\C
hannelUpdate.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

C:\Users\hellow\Desktop\T.A.P Bot\T.A.P Bot>

**Comment by Superbrain8** [comment]
> Im getting this
> Bot is ready!
> DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'cleverbot.io'. Please wait...
> DBM MODS (Node Module Installer v2.1): Node Module 'cleverbot.io' does not exist!
> Command failed: npm install cleverbot.io --loglevel=error --save
> DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'cleverbot.io'. Please wait...
> DBM MODS (Node Module Installer v2.1): Node Module 'cleverbot.io' does not exist!
> Command failed: npm install cleverbot.io --loglevel=error --save
> Error with Event "Cleverbot", Action #1: Error: Cannot find module 'cleverbot.io'
> DBM MODS (Node Module Installer v2.1): Could not automatically install cleverbot.io. (Install attempt limit reached) Please try to run your bot CMD/Terminal (Ctrl + Shift + Right Click [In Windows] To Open a CMD Window) and do 'node bot.js' at least once to allow the installer to run. If that still fails please do 'npm install --save cleverbot.io' and restart your bot before you continue.
> DBM MODS (Node Module Installer v2.1): Could not automatically install cleverbot.io. (Install attempt limit reached) Please try to run your bot CMD/Terminal (Ctrl + Shift + Right Click [In Windows] To Open a CMD Window) and do 'node bot.js' at least once to allow the installer to run. If that still fails please do 'npm install --save cleverbot.io' and restart your bot before you continue.
> Error with Event "Cleverbot", Action #1: Error: Cannot find module 'cleverbot.io'

did you tryed to install the modules manually over cmd?

**Comment by Superbrain8** [comment]
> I get this when i try and node
> C:\Users\hellow\Desktop\T.A.P Bot\T.A.P Bot>node bot.js
> internal/modules/cjs/loader.js:596
> throw err;
> ^
> 
> Error: Cannot find module '../../util/Constants'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
> at Function.Module._load (internal/modules/cjs/loader.js:520:25)
> at Module.require (internal/modules/cjs/loader.js:650:17)
> at require (internal/modules/cjs/helpers.js:20:18)
> at Object. (C:\Users\hellow\Desktop\T.A.P Bot\T.A.P Bot\actions\C
> hannelUpdate.js:2:19)
> at Module._compile (internal/modules/cjs/loader.js:702:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
> at Module.load (internal/modules/cjs/loader.js:612:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
> at Function.Module._load (internal/modules/cjs/loader.js:543:3)
> 
> C:\Users\hellow\Desktop\T.A.P Bot\T.A.P Bot>

seems like a Corrupted Bot, reinstalling Modules could fix it in worst case you need to make a new Bot. (For more help better ask in Discord)
