### ISSUE TITLE
Custom Image Effects: src must be a string or a Buffer

### ISSUE THREAD

**Issue by TheMonDon** [dbm-network/mods#208]
Custom image effects mod by lasse has source image variable, but creating image from avatar or from url yields same result of "src must be a string or a Buffer"
```

(node:31115) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blur' of undefined
    at /home/john/discord/CISN/main/actions/custom_image_effects_MOD.js:155:11
    at throwError (/home/john/discord/CISN/main/node_modules/jimp/index.js:85:44)
    at /home/john/discord/CISN/main/node_modules/jimp/index.js:238:35
    at new Promise (<anonymous>)
    at Function.Jimp.read (/home/john/discord/CISN/main/node_modules/jimp/index.js:231:19)
    at Object.action [as Custom Image Effects] (/home/john/discord/CISN/main/actions/custom_image_effects_MOD.js:151:7)
    at Object.Actions.callNextAction (/home/john/discord/CISN/main/bot.js:493:18)
    at Object.<anonymous> (/home/john/discord/CISN/main/actions/create_image.js:113:8)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:31115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by Almeeida** [comment]
Have you tried storing the user's avatar using Store Member Info -> Create Image (using the URL)?
