### ISSUE TITLE
Store Game Server Info not working.

### ISSUE THREAD

**Issue by andretunes** [dbm-network/mods#258]
Hello,
When i query a csgo server or any other game server gives me this error:
`(node:26197) UnhandledPromiseRejectionWarning: Error: No game specified
    at GameResolver.lookup (/root/bot-discord-oakcm/node_modules/gamedig/lib/GameResolver.js:12:25)
    at QueryRunner.run (/root/bot-discord-oakcm/node_modules/gamedig/lib/QueryRunner.js:29:31)
    at Gamedig.query (/root/bot-discord-oakcm/node_modules/gamedig/lib/index.js:11:39)
    at Function.query (/root/bot-discord-oakcm/node_modules/gamedig/lib/index.js:19:44)
    at Object.action [as Store Game Server Info] (/root/bot-discord-oakcm/actions/game_server_MOD.js.1:236:11)
    at Object.Actions.callNextAction (/root/bot-discord-oakcm/bot.js:493:18)
    at Object.<anonymous> (/root/bot-discord-oakcm/actions/send_embed_message.js:187:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

But i have specified the gametype why this happen?

Kind regards.

**Comment by ForceBlood** [comment]
Can you please provide a screenshot of your store game server info action?

**Comment by andretunes** [comment]
Hello, yes i can:
https://prnt.virtual4host.pt/yvcpr.png

Regards

**Comment by ForceBlood** [comment]
Your game server info mod is outdated. Please update it from: https://github.com/Discord-Bot-Maker-Mods/DBM-Mods/tree/beta?files=1

**Comment by andretunes** [comment]
Ohh many thanks! I will update and reply ASAP. Regards.

No dia sexta-feira, 13 de dezembro de 2019, ForceBlood <
notifications@github.com> escreveu:

**Comment by andretunes** [comment]
Hello stills the same dont get info but dont give any error.
regards

**Comment by Almeeida** [comment]
Have you updated the action on your project's directory as well?

**Comment by andretunes** [comment]
Hello, yes.
Regards

**Comment by ForceBlood** [comment]
Sorry, I wasn't active on Github for a long time. If you are still having issues, can you please provide me the server ip and the port so I can do some tests.

**Comment by Almeeida** [comment]
This issue will be closed since it has been opened for more than 10 days with no activity. If your issue still persists, feel free to reopen the issue.

**Comment by Ryzesx** [comment]
can you help me with getting my five player list in a channel?

![image](https://user-images.githubusercontent.com/66752177/87749345-70e92100-c7c6-11ea-9178-0cf94f84e724.png)

**Comment by Almeeida** [comment]
@Ryzesx use our [Discord server](https://discord.gg/3QxkZPK) to get help
