### ISSUE TITLE
TypeError: this.getWrexMods is not a function | Problem with "play Youtube video."

### ISSUE THREAD

**Issue by horvik-pyysalo** [dbm-network/mods#272]
Hey, 
I try to put a music option on my bot with DBM, I followed the tutorial on youtube of lasse, the bot join a channel but nothing happens, it's been 1-2 hours that I'm looking for (install WrexMods ect ) but nothing happens. 

can you help me? 

I also have an error in the console:

`

0|bot  | TypeError: this.getWrexMods is not a function
0|bot  |     at Object.action [as Play YouTube Video] (/home/gaetan/hb_discord/heavybot-discordbot/actions/play_youtube.js:136:31)
0|bot  |     at Object.Actions.callNextAction (/home/gaetan/hb_discord/heavybot-discordbot/bot.js:493:4)
0|bot  |     at Object.<anonymous> (/home/gaetan/hb_discord/heavybot-discordbot/actions/join_voice_channel.js:103:9) `

**Comment by Almeeida** [comment]
Are you using DBM Beta?

**Comment by horvik-pyysalo** [comment]
yes
![image](https://user-images.githubusercontent.com/52079576/74606764-599cef00-50d3-11ea-9331-8a27fe9bb298.png)
and I also checked the integrity of the application's files.

**Comment by Almeeida** [comment]
You are, most likely, missing this action on the actions folders. 
https://github.com/dbm-network/mods/blob/beta/actions/aaa_wrexmods_dependencies_MOD.js

**Comment by horvik-pyysalo** [comment]
I just installed the mod in "action directory" and in "project directory " in action folder, the console asked me to install ytdl-core when it was already installed, I unistalle / reinstall it and here's what it tells me 

`0|bot  | DBM MODS (Node Module Installer v2.5) Attempting To Install Node Module: 'ytdl-core'. Please wait...
0|bot  | npm
0|bot  |  ERR! code EACCES
0|bot  | npm
0|bot  |  ERR!
0|bot  | syscall access
0|bot  | npm
0|bot  |  ERR!
0|bot  | path /usr/lib/node_modules/pm2/node_modules
0|bot  | npm
0|bot  |  ERR! errno -13
0|bot  | npm
0|bot  | ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/pm2/node_modules'
0|bot  | npm
0|bot  | ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules/pm2/node_modules']
0|bot  | npm
0|bot  |  ERR!   stack:
0|bot  | npm ERR!
0|bot  |     'Error: EACCES: permission denied, access \'/usr/lib/node_modules/pm2/node_modules\'',
0|bot  | npm ERR!
0|bot  |    errno: -13,
0|bot  | npm ERR!
0|bot  |    code: 'EACCES',
0|bot  | npm ERR!
0|bot  |    syscall: 'access',
0|bot  | npm
0|bot  | ERR!   path: '/usr/lib/node_modules/pm2/node_modules' }
0|bot  | npm ERR!
0|bot  |
0|bot  | npm ERR!
0|bot  |  The operation was rejected by your operating system.
0|bot  | npm
0|bot  | ERR! It is likely you do not have the permissions to access this file as the current user
0|bot  | npm
0|bot  | ERR!
0|bot  | npm
0|bot  | ERR! If you believe this might be a permissions issue, please double-check the
0|bot  | npm
0|bot  |  ERR! permissions of the file and its containing directories, or try running
0|bot  | npm
0|bot  |  ERR! the command again as root/Administrator.
0|bot  | npm ERR! A complete log of this run can be found in:
0|bot  | npm ERR!     /home/gaetan/.npm/_logs/2020-02-16T16_36_48_019Z-debug.log
0|bot  | DBM MODS (Node Module Installer v2.5): Node Module  'ytdl-core' does not exist!
0|bot  | Command failed: npm install ytdl-core --loglevel=error --save
0|bot  | { Error: Cannot find module '/usr/lib/node_modules/pm2/lib/node_modules/ytdl-core'
0|bot  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
0|bot  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|bot  |     at Object.WrexMODS.require (/home/gaetan/hb_discord/heavybot-discordbot/actions/aaa_wrexmods_dependencies_MOD.js:122:22)
0|bot  |     at Object.action [as Play YouTube Video] (/home/gaetan/hb_discord/heavybot-discordbot/actions/play_youtube.js:137:31)
0|bot  |     at Object.Actions.callNextAction (/home/gaetan/hb_discord/heavybot-discordbot/bot.js:493:4)
0|bot  |     at Object.<anonymous> (/home/gaetan/hb_discord/heavybot-discordbot/actions/join_voice_channel.js:103:9) code: 'MODULE_NOT_FOUND' }
`

**Comment by Almeeida** [comment]
Run `sudo npm i ytdl-core`

**Comment by horvik-pyysalo** [comment]
yes I've already done "sudo npm i ytdl-core" but the error is the same.

**Comment by Almeeida** [comment]
Still getting `Error: EACCES: permission denied` after running with sudo?

**Comment by Almeeida** [comment]
This issue will be closed since it has been opened for more than 10 days with no activity. If your issue still persists, feel free to reopen the issue.

**Comment by DareFox** [comment]
I have the same error, the bot (or the WrexMods Dependencies script) does not see the modules when it is launched via pm2 on **Linux VPS**.

Via sudo pm2 start bot.js is the same.

![ApplicationFrameHost_qXgpTKIYn3](https://user-images.githubusercontent.com/47672780/83202086-82f7fd00-a14f-11ea-8182-6899bb65121d.png)

**Comment by Almeeida** [comment]
> I have the same error, the bot (or the WrexMods Dependencies script) does not see the modules when it is launched via pm2 on **Linux VPS**.
> 
> Via sudo pm2 start bot.js is the same.
> 
> ![ApplicationFrameHost_qXgpTKIYn3](https://user-images.githubusercontent.com/47672780/83202086-82f7fd00-a14f-11ea-8182-6899bb65121d.png)

https://github.com/dbm-network/mods/issues/337
