### ISSUE TITLE
Create Embed Message errors

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#516]
Not sure if it's this mod only, or if there are more mods.

I tried using the node command below because i keep getting Unhandled PromiseRejectionWarning warnings.

`node --trace-warnings bot.js`

![1](https://user-images.githubusercontent.com/4199669/89322099-12f08080-d684-11ea-8ca8-eab0b2af64a0.JPG)

![2](https://user-images.githubusercontent.com/4199669/89322115-15eb7100-d684-11ea-842e-6109325f7e93.JPG)

```
TypeError: Cannot read property 'author' of undefined
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10), <anonymous>:1:8                                       )
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10)
    at Object.Actions.evalMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:354:14)
    at Object.action [as Create Embed Message] (/home/dashboard.newstargeted.com/public_html/nt1/actions/create_emb                                       ed_message.js:230:30)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Save Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/save_variable.js:                                       105:8)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Control Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/control_variab                                       le.js:139:8)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Store Member Info] (/home/dashboard.newstargeted.com/public_html/nt1/actions/store_member_                                       info.js:371:8)
TypeError: Cannot read property 'author' of undefined
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10), <anonymous>:1:8                                       )
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10)
    at Object.Actions.evalMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:354:14)
    at Object.action [as Set Embed Description] (/home/dashboard.newstargeted.com/public_html/nt1/actions/set_embed                                       _description.js:102:30)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Create Embed Message] (/home/dashboard.newstargeted.com/public_html/nt1/actions/create_emb                                       ed_message.js:268:12)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Save Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/save_variable.js:                                       105:8)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Control Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/control_variab                                       le.js:139:8)
SyntaxError: Invalid or unexpected token
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:15)
    at Object.action [as Add Item to List] (/home/dashboard.newstargeted.com/public_html/nt1/actions/add_item_to_li                                       st.js:131:15)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt1/actions/action_list_comment_MOD                                       .js:24:10)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Create List] (/home/dashboard.newstargeted.com/public_html/nt1/actions/create_list.js:106:                                       8)
    at Object.Actions.invokeActions (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:502:18)
    at Object.Actions.preformActions (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:391:8)
    at Object.Bot.onAnyMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:209:13)
    at Object.Bot.onMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:166:10)
TypeError: Cannot read property 'author' of undefined
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10), <anonymous>:1:8)
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10)
    at Object.Actions.evalMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:354:14)
    at Object.action [as Create Embed Message] (/home/dashboard.newstargeted.com/public_html/nt1/actions/create_embed_message.js:230:30)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Save Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/save_variable.js:105:8)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Control Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/control_variable.js:139:8)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Store Member Info] (/home/dashboard.newstargeted.com/public_html/nt1/actions/store_member_info.js:371:8)
TypeError: Cannot read property 'author' of undefined
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10), <anonymous>:1:8)
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:10)
    at Object.Actions.evalMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:354:14)
    at Object.action [as Set Embed Description] (/home/dashboard.newstargeted.com/public_html/nt1/actions/set_embed_description.js:102:30)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Create Embed Message] (/home/dashboard.newstargeted.com/public_html/nt1/actions/create_embed_message.js:268:12)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Save Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/save_variable.js:105:8)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Control Variable] (/home/dashboard.newstargeted.com/public_html/nt1/actions/control_variable.js:139:8)
SyntaxError: Invalid or unexpected token
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:344:15)
    at Object.action [as Add Item to List] (/home/dashboard.newstargeted.com/public_html/nt1/actions/add_item_to_list.js:131:15)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt1/actions/action_list_comment_MOD.js:24:10)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:547:18)
    at Object.action [as Create List] (/home/dashboard.newstargeted.com/public_html/nt1/actions/create_list.js:106:8)
    at Object.Actions.invokeActions (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:502:18)
    at Object.Actions.preformActions (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:391:8)
    at Object.Bot.onAnyMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:209:13)
    at Object.Bot.onMessage (/home/dashboard.newstargeted.com/public_html/nt1/bot.js:166:10)
```

**Comment by LeonZ2019** [comment]
erm are you sure you send to correct command screenshot?
![image](https://user-images.githubusercontent.com/10143361/89322648-19e4b680-d6b7-11ea-985c-979ea8045a04.png)

**Comment by master3395** [comment]
It was the right command.

But i have tried 2 different types of "ping" commands.

And the errors i got on the list, was from another ping command i have, that has a standard message with an embed i got.

Below is only from the image here.

![3](https://user-images.githubusercontent.com/4199669/89323440-fead8300-d685-11ea-8090-f5ac36ea8257.JPG)

**Comment by RigidStudios** [comment]
This is your fault. Every single error is your fault. Also, it **is** the wrong command that you are showing us, the trace doesn't share a single action name.
- Error 1: Messed up Template Literal.
- Error 2: Messed up Template Literal.
- Error 3: You forgot a quote in add item to list or used a template literal without a back-quoted string.
- Error 4: Messed up Template Literal.
- Error 5: Messed up Template Literal.
- Error 6: You forgot a quote in add item to list or used a template literal without a back-quoted string.

Refer to support channels.
