### ISSUE TITLE
and this

### ISSUE THREAD

**Issue by zink-debug** [dbm-network/mods#601]
TypeError: msg.awaitReactions is not a function
    at Object.action [as Await Reaction Call Action] (C:\Users\person\OneDrive\Documents\Desktop\bot storage\reink\actions\await_reaction_call_action_MOD.js:212:11)
    at Object.Actions.callNextAction (C:\Users\person\OneDrive\Documents\Desktop\bot storage\reink\bot.js:547:18)
    at Object.action [as Add Reaction] (C:\Users\person\OneDrive\Documents\Desktop\bot storage\reink\actions\add_reaction.js:156:9)
    at Object.Actions.callNextAction (C:\Users\person\OneDrive\Documents\Desktop\bot storage\reink\bot.js:547:18)
    at C:\Users\person\OneDrive\Documents\Desktop\bot storage\reink\actions\send_embed_message.js:147:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Mindlesscargo** [comment]
Please ask for support on the Discord before posting bug reports.

**Comment by RigidStudios** [comment]
Your fault, message doesn't exist. @Mindlesscargo close this or get another team member to do so.
