### ISSUE TITLE
Error with the command "Canvas Create Image", Action #22

### ISSUE THREAD

**Issue by HerobrineTV** [dbm-network/mods#608]
**Describe the bug**
I cannot Create Canvas Images

**To Reproduce**
1. Do Create Canvas Image
2. Run the Command
3. See the Error

**Expected behavior**
I wanted to resize text etc so i needed to use canvas and wrote my whole command with canvas but now it doesnt send a picture and my bot says an error

**Screenshots**

Its not a Screenshot but it might help u:

Console Output:

`Error: Cannot find module 'canvas'
Require stack:
- C:\Users\CENSORED\Discord Bots\HeroesBot\actions\canvas_create_image_MOD.js
- C:\Users\CENSORED\Discord Bots\HeroesBot\bot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.action [as Canvas Create Image] (C:\Users\CENSORED\Discord Bots\HeroesBot\actions\canvas_create_image_MOD.js:42:20)
    at Object.Actions.callNextAction (C:\Users\CENSORED\Discord Bots\HeroesBot\bot.js:547:18)
    at Object.action [as Comment] (C:\Users\CENSORED\Discord Bots\HeroesBot\actions\action_list_comment_MOD.js:24:10)
    at Object.Actions.callNextAction (C:\Users\CENSORED\Discord Bots\HeroesBot\bot.js:547:18)
    at C:\Users\CENSORED\Discord Bots\HeroesBot\actions\send_image.js:177:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by Mindlesscargo** [comment]
Did you even attempt to get support before posting this? Clearly not.

**Comment by TheHQE** [comment]
"npm i canvas" in your console
