### ISSUE TITLE
"Send Image" per DM throws a timout error

### ISSUE THREAD

**Issue by M123-dev** [dbm-network/mods#612]
**Describe the bug**
_I'm not exactly sure if it's more of a bug or a suggested feature._ 

Does not matter, so the topic is if I use "Send Image" to specify user as the "Send To:", nothing happens.

If I use the default channel for "Send To:" instead of Temp Var, the photo is also sent.
Also, if I send a text with "Send Message" instead of a photo it works, so the member-object must be fine. 

After a long time (approx. 1 minute) there is a timeout error code. This one here:

```
(node:13232) UnhandledPromiseRejectionWarning: Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at D:\111Programming\Discord\Bot\FrozenWater\node_modules\discord.js\src\managers\GuildMemberManager.js:265:16
    at Timeout._onTimeout (D:\111Programming\Discord\Bot\FrozenWater\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:13232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
The expected behavior should be that the picture should get sent per Direct message.

**Comment by M123-dev** [comment]
It seems like this is not a problem with "Send Image" but one with the process of finding the member. [Issue about that](https://github.com/discordjs/discord.js/issues/3774)
