### ISSUE TITLE
Youtube Play action is broken Right Now

### ISSUE THREAD

**Issue by erturkgg** [dbm-network/mods#708]
Error with the command "Play YouTube Video", Action #2

Error: Status code: 404
    at ClientRequest.<anonymous> (C:\Users\Ertürk\Documents\MorukCJ\node_modules\miniget\dist\index.js:210:27)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)

I tried Despacito, Shape of You and other songs, same issue. Also its happening to 4 people on DBM Mods Discord right now.

**Comment by erturkgg** [comment]
Temp fix: https://github.com/fent/node-ytdl-core/commit/d1f535712410eebd79a7468abd07d94f8c4ebe5a

**Comment by TheMonDon** [comment]
Going to leave this open as it is useful info and for others don't make an issue that it's broken.

It is indeed due to ytdl-core I'm sure.

**Comment by TheMonDon** [comment]
Fixed by updating ytdl-core to latest version.
