### ISSUE TITLE
aaa_dbmmods_dependencies_MOD - this.installModule is not a function

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#772]
Not sure what is causing this, if it's in the file or if it's a code in the bot that can trigger this.
I do not remember using this.install anywhere.

TypeError: this.installModule is not a function
    at require (/home/dashboard.newstargeted.com/public_html/nt/actions/aaa_dbmmods_dependencies_MOD.js:19:12)
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:6:13)
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:155:3)
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10)
    at Object.action [as Run Script] (/home/dashboard.newstargeted.com/public_html/nt/actions/run_script.js:287:12)
    at Object.Actions.invokeActions (/home/dashboard.newstargeted.com/public_html/nt/bot.js:502:18)
    at Object.Actions.preformActions (/home/dashboard.newstargeted.com/public_html/nt/bot.js:391:8)
    at Object.Bot.onAnyMessage (/home/dashboard.newstargeted.com/public_html/nt/bot.js:209:13)
    at Object.Bot.onMessage (/home/dashboard.newstargeted.com/public_html/nt/bot.js:166:10)
    at Client.emit (node:events:394:28)

**Comment by RediPanda** [comment]
@master3395, is this issue still reproducible?

**Comment by master3395** [comment]
Forgot to write here, I wrote on discord that it still happens on 1.6 and 2.0.2

This is from 2.0.2 today :)


TypeError: this.installModule is not a function
    at require (/home/dashboard.newstargeted.com/public_html/nt1/actions/aaa_dbmmods_dependencies_MOD.js:19:12)
