### ISSUE TITLE
Check If Member not working

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#805]
**Describe the bug**
Using Check if member is not working, the error is shown below, along with an image.

TypeError: this.dest is not a function
    at Object.action [as Check If Member] (/home/dashboard.newstargeted.com/public_html/nt2/actions/check_if_member_MOD.js:136:23)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1319:21)
    at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt2/actions/action_list_comment_MOD.js:24:10)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1319:21)
    at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt2/actions/action_list_comment_MOD.js:24:10)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1319:21)
    at Object.action [as Comment] (/home/dashboard.newstargeted.com/public_html/nt2/actions/action_list_comment_MOD.js:24:10)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1319:21)
    at Object.Actions.invokeActions (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1269:10)
    at Object.Actions.preformActionsFromMessage (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1142:10)

**To Reproduce**
1. Start DBM
2. Click on Actions
3. Add Action "Check If Member"
4. Add some way of checking for the member.
5. Output the result as "If the member is = send message"

**Expected behavior**
Check if a member using the command is a bot.
Then stop the action (If set up that way)

**Screenshots**
![image](https://user-images.githubusercontent.com/4199669/145444027-0e18d273-ad09-4c98-b127-317e02cd84d1.png)

**Comment by master3395** [comment]
I'm using it to check if the author is a different bot, so it can't execute my "Dig system".
Checking if they are bannable would not be the same.

**Comment by almeidx** [comment]
If you are still having this issue, you are using an outdated action
