### ISSUE TITLE
Set Time Restriction for V2.x author error

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#842]
When trying to set cooldown on users that use Slash and without slash.
Set Time Restriction cannot find the author, because it uses `msg.author.id`
V16 uses `${user.id}`

I tried changing it to user.id but I messed it up on my end.
Below is how it looks inside of the current release.

![image](https://user-images.githubusercontent.com/4199669/149374861-0a423c52-f430-4dea-9dd8-59a56e79ce86.png)

![image](https://user-images.githubusercontent.com/4199669/149375361-8b132e1c-9b0e-47f3-b8f4-88ea1d30b698.png)

Error message 1

```
TypeError: Cannot read properties of null (reading 'author')
    at Object.TimeRestriction (/home/dashboard.newstargeted.com/public_html/nt2/actions/set_time_restriction_MOD.js:264:45)
    at Object.action [as Set Time Restriction] (/home/dashboard.newstargeted.com/public_html/nt2/actions/set_time_restriction_MOD.js:197:27)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1467:21)
    at Object.Actions.invokeInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1439:8)
    at Object.Actions.preformActionsFromInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1300:12)
    at Object.Bot.onSlashCommandInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:892:13)
    at Object.Bot.onInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:859:10)
    at Client.emit (node:events:390:28)
    at InteractionCreateAction.handle (/home/dashboard.newstargeted.com/public_html/nt2/node_modules/discord.js/src/client/actions/InteractionCreate.js:74:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/dashboard.newstargeted.com/public_html/nt2/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
```

Error message 2

```
TypeError: Cannot read properties of null (reading 'user')
    at Object.TimeRestriction (/home/dashboard.newstargeted.com/public_html/nt2/actions/set_time_restriction_MOD.js:264:45)
    at Object.action [as Set Time Restriction] (/home/dashboard.newstargeted.com/public_html/nt2/actions/set_time_restriction_MOD.js:197:27)
    at Object.Actions.callNextAction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1467:21)
    at Object.Actions.invokeInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1439:8)
    at Object.Actions.preformActionsFromInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:1300:12)
    at Object.Bot.onSlashCommandInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:892:13)
    at Object.Bot.onInteraction (/home/dashboard.newstargeted.com/public_html/nt2/bot.js:859:10)
    at Client.emit (node:events:390:28)
    at InteractionCreateAction.handle (/home/dashboard.newstargeted.com/public_html/nt2/node_modules/discord.js/src/client/actions/InteractionCreate.js:74:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/dashboard.newstargeted.com/public_html/nt2/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
```

**Comment by DetroitWhiskey136** [comment]
Fix Coming Soon TM

**Comment by DetroitWhiskey136** [comment]
#848
