### ISSUE TITLE
Not start only on server?

### ISSUE THREAD

**Issue by xorgxx** [dbm-network/mods#856]
Hi when i start on my server nas synology it das not start.
it start on my local pc windows 10 64b

server config node16

i make export to node. unzip the file on my server nas synology. command node bot.js 

this is in the log 

```
Error: ENOENT: no such file or directory, open '/usr/syno/synoman/webapi/data/globals.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at Object.mod (/volume1/norx/Discord/Bot-neox/actions/delete_global_data_MOD.js:44:10)
    at /volume1/norx/Discord/Bot-neox/bot.js:1265:18
    at Array.forEach (<anonymous>)
    at /volume1/norx/Discord/Bot-neox/bot.js:1254:25
    at Array.forEach (<anonymous>)
    at Object.Actions.initMods (/volume1/norx/Discord/Bot-neox/bot.js:1253:25)
    at Object.Files.startBot (/volume1/norx/Discord/Bot-neox/bot.js:2582:13)
    at Object.<anonymous> (/volume1/norx/Discord/Bot-neox/bot.js:3553:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/syno/synoman/webapi/data/globals.json'
}
TypeError: Mods.setupMusic is not a function
    at Object.mod (/volume1/norx/Discord/Bot-neox/actions/loop_queue_MOD.js:85:10)
    at /volume1/norx/Discord/Bot-neox/bot.js:1265:18
    at Array.forEach (<anonymous>)
    at /volume1/norx/Discord/Bot-neox/bot.js:1254:25
    at Array.forEach (<anonymous>)
    at Object.Actions.initMods (/volume1/norx/Discord/Bot-neox/bot.js:1253:25)
    at Object.Files.startBot (/volume1/norx/Discord/Bot-neox/bot.js:2582:13)
    at Object.<anonymous> (/volume1/norx/Discord/Bot-neox/bot.js:3553:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
/volume1/norx/Discord/Bot-neox/node_modules/discord.js/src/client/Client.js:237
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/volume1/norx/Discord/Bot-neox/node_modules/discord.js/src/client/Client.js:237:52)
    at Object.Bot.login (/volume1/norx/Discord/Bot-neox/bot.js:617:12)
    at Object.Bot.init (/volume1/norx/Discord/Bot-neox/bot.js:263:8)
    at setData (/volume1/norx/Discord/Bot-neox/bot.js:2605:9)
    at Object.Files.readData (/volume1/norx/Discord/Bot-neox/bot.js:2610:7)
    at Object.Files.startBot (/volume1/norx/Discord/Bot-neox/bot.js:2583:10)
    at Object.<anonymous> (/volume1/norx/Discord/Bot-neox/bot.js:3553:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  [Symbol(code)]: 'TOKEN_INVALID'
```

Thank

**Comment by Sneethan** [comment]
First off, you need to make sure you copy your data folder across from your bot project.
Second you need to put it your bot token, save it then copy that. You dont need to use export just copy the things from your project directory

**Comment by xorgxx** [comment]
thank's. so i deed as you said. all is the controle all good !! still the error 

```
Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/volume1/norx/Discord/Bot-neox/node_modules/discord.js/src/client/Client.js:237:52)
    at Object.Bot.login (/volume1/norx/Discord/Bot-neox/bot.js:617:12)
    at Object.Bot.init (/volume1/norx/Discord/Bot-neox/bot.js:263:8)
    at setData (/volume1/norx/Discord/Bot-neox/bot.js:2605:9)
    at Object.Files.readData (/volume1/norx/Discord/Bot-neox/bot.js:2610:7)
    at Object.Files.startBot (/volume1/norx/Discord/Bot-neox/bot.js:2583:10)
    at Object.<anonymous> (/volume1/norx/Discord/Bot-neox/bot.js:3553:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  [Symbol(code)]: 'TOKEN_INVALID'
```

**Comment by Sneethan** [comment]
It means that you aren’t giving it a valid bot token, try refreshing it in the developer portal. Then put it in the settings tab of DBM.



________________________________

**Comment by xorgxx** [comment]
the setting.json clone of the one i have on station. 1,31 Ko (1 349 octets) on station - 1,31 Ko (1 349 octets) on server

**Comment by xorgxx** [comment]
to be complite, i have just make copy/paste form the .../data/settings.json key "token" inside (on server version) and paste inside bot.js -> 
form 

```
Bot.login = function () {
  this.bot.login(Files.data.settings.token);
};
```
to 
```
Bot.login = function () {
  this.bot.login("TOKEN KEY FORM SETTINGS.JSON");
};
```
it work !! ?????

**Comment by xorgxx** [comment]
so just made copy of settings.json and paste not on the same pc (windows 10 64b, node 16) and it work !!! no probleme token as find

**Comment by xorgxx** [comment]
i have created on docker image of node last version start the config from my local pc (dev version) guest what ??!! the same error.
on this pc it start and work !!! with Discord maker bot !!!

**Comment by xorgxx** [comment]
and to finish all test : i have start copy on the server with DBM from my local pc (by network) and slow but it start and work !!! so for shur the settings.json is well setup !!!

**Comment by xorgxx** [comment]
just for info DBM ver. 2.1.1

**Comment by Sneethan** [comment]
Nooo put your token inside settings.json in the data folder

Sent from my iPhone

On 5 Mar 2022, at 1:43 am, xorgxx ***@***.***> wrote:

﻿

just for info DBM ver. 2.1.1

**Comment by xorgxx** [comment]
so and now ? what do i do ??? i still have my probleme, and i know that it's not probleme of my settings.json, not probleme of server config, not probleme of discord rules ....... 

???? stay lake this ?

**Comment by DetroitWhiskey136** [comment]
this isn't a mod bug it has to do with how your bot is configured in your server... if you require further support please use one of the DBM guilds.
