### ISSUE TITLE
[BUG] Twitch Actions

### ISSUE THREAD

**Issue by DonKolia** [dbm-network/mods#921]
This sounds absurd, but it is simple and it is not necessary to send or specify with many words. Twitch actions don't work at all, I'm using the latest version of DBM. This happens all the time, with any twitch action, it's a clean project and it doesn't work.

Starting bot at version: "2.1.6"
 ? TypeError: Actions.getMods is not a function
 ?     at Object.mod (C:\Users\DonKolia\Desktop\pruebas\events\cron_scheduler_EVT.js:13:26)
 ?     at C:\Users\DonKolia\Desktop\pruebas\bot.js:1310:18
 ?     at Array.forEach (<anonymous>)
 ?     at C:\Users\DonKolia\Desktop\pruebas\bot.js:1299:25
 ?     at Array.forEach (<anonymous>)
 ?     at Object.Actions.initMods (C:\Users\DonKolia\Desktop\pruebas\bot.js:1298:25)
 ?     at Object.Files.startBot (C:\Users\DonKolia\Desktop\pruebas\bot.js:2705:13)
 ?     at Object.<anonymous> (C:\Users\DonKolia\Desktop\pruebas\bot.js:3715:7)
 ?     at Module._compile (node:internal/modules/cjs/loader:1097:14)
 ?     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
 ? 
 ? C:\Users\DonKolia\Desktop\pruebas\actions\twitch_authentication_MOD.js:88
 ?     const Mods = this.getMods();
 ?                       ^
 ? 
 ? TypeError: this.getMods is not a function
 ?     at Object.action [as Twitch Authentication] (C:\Users\DonKolia\Desktop\pruebas\actions\twitch_authentication_MOD.js:88:23)
 ?     at Object.Actions.callNextAction (C:\Users\DonKolia\Desktop\pruebas\bot.js:1509:21)
 ?     at Object.Actions.invokeInteraction (C:\Users\DonKolia\Desktop\pruebas\bot.js:1481:8)
 ?     at Object.Actions.preformActionsFromInteraction (C:\Users\DonKolia\Desktop\pruebas\bot.js:1342:12)
 ?     at Object.Bot.onSlashCommandInteraction (C:\Users\DonKolia\Desktop\pruebas\bot.js:969:13)
 ?     at Object.Bot.onInteraction (C:\Users\DonKolia\Desktop\pruebas\bot.js:934:10)
 ?     at Client.emit (node:events:520:28)
 ?     at InteractionCreateAction.handle (C:\Users\DonKolia\Desktop\pruebas\node_modules\discord.js\src\client\actions\InteractionCreate.js:83:12)
 ?     at Object.module.exports [as INTERACTION_CREATE] (C:\Users\DonKolia\Desktop\pruebas\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
 ?     at WebSocketManager.handlePacket (C:\Users\DonKolia\Desktop\pruebas\node_modules\discord.js\src\client\websocket\WebSocketManager.js:346:31)
 ? 
 ? Node.js v17.4.0
 ?

**Comment by DonKolia** [comment]
And i am using the last version mods
